[project]
name = "agents4plc-release"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "langchain-chroma>=1.0.0",
    "langchain-openai>=1.0.1",
    "requests>=2.32.5",
]
